### ISSUE TITLE
v2.9.2's .version file

### ISSUE THREAD

**Issue by mheguy** [xytovl/SmartStage#5]
The version file indicates the release is only compatible with `KSP_VERSION` `1.1.1000`. As CKAN takes compatibility information from the .version file our users won't be able to install your mod. I'd like to set up an override but just want to be sure I have the correct meaning from the version you set. Would a `ksp_version_min` of `1.1.0` and a `ksp_version_max` of `1.1.99` cover the expected compatibility of this release?

**Comment by xytovl** [comment]
I didn't know about the min/max versions. I'll use them instead, I wanted to ignore the minor version...

**Comment by xytovl** [comment]
I have added min/max versions in AVC format:
"KSP_VERSION":
    {
        "MAJOR":1,
        "MINOR":1,
        "PATCH":0
    },
    "KSP_VERSION_MIN":
    {
        "MAJOR":1,
        "MINOR":1,
        "PATCH":0
    },
    "KSP_VERSION_MAX":
    {
        "MAJOR":1,
        "MINOR":1,
        "PATCH":1000
    }

The override should not be required anymore
