### ISSUE TITLE
Applauncher button not obeying settings

### ISSUE THREAD

**Issue by Gribbleshnibit8** [xytovl/SmartStage#8]
I've set the AppLauncher button to not be visible in flight and it still is. Additionally, it doesn't seem to be disposing of the button correctly. Transitioning from Flight to Space Center leaves the button in the AppLauncher until the scene changes to editor and back to Space Center again.

**Comment by xytovl** [comment]
fixed by 6561b2bd015635c018214319263d546618dc3cac
